# Generated by Django 5.0.1 on 2024-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='limite_reserva',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='preco_aluguel',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
