# Generated by Django 5.0.1 on 2024-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
